@startuml

header
<font color=red>2021/08/09 10:43:53</font>
endheader

title = State Diagram: gen2

[*] --> idle

idle --> fault : error<0
idle --> restart : do_restart
idle --> startup_check
idle : no_closing=False
patient_setup --> fault : error<0
patient_setup --> restart : do_restart
init --> fault : error<0
init --> restart : do_restart
init --> ready
startup_check --> fault : error<0
startup_check --> restart : do_restart
startup_check --> init
restart --> fault : error<0
restart --> idle
ready --> fault : error<0
ready --> restart : do_restart
ready --> patient_init : new_patient==1
init_instrument --> fault : error<0
init_instrument --> restart : do_restart
init_instrument --> patient_morpho_init : not patient_installed 
init_instrument --> back_camera : patient_installed 
exit_instrument --> fault : error<0
exit_instrument --> restart : do_restart
exit_instrument --> prepare_examination
patient_init --> fault : error<0
patient_init --> restart : do_restart
patient_init --> prepare_examination
patient_morpho_init --> fault : error<0
patient_morpho_init --> restart : do_restart
patient_morpho_init --> patient_setup_adjustment
patient_morpho_init : chinrest_adjusted=False
patient_setup_adjustment --> fault : error<0
patient_setup_adjustment --> restart : do_restart
patient_setup_adjustment --> patient_wait
chinrest_adjustment --> fault : error<0
chinrest_adjustment --> restart : do_restart
chinrest_adjustment --> back_camera
patient_wait --> fault : error<0
patient_wait --> restart : do_restart
patient_wait --> back_camera
dummy_examination --> fault : error<0
dummy_examination --> restart : do_restart
patient_departure --> fault : error<0
patient_departure --> restart : do_restart
patient_departure --> patient_left
prepare_examination --> fault : error<0
prepare_examination --> restart : do_restart
prepare_examination --> init_instrument : not all_examination_done               
prepare_examination --> patient_departure : all_examination_done
patient_left --> fault : error<0
patient_left --> restart : do_restart
patient_left --> neutral_x
neutral_x --> fault : error<0
neutral_x --> restart : do_restart
neutral_x --> neutral_y
neutral_y --> fault : error<0
neutral_y --> restart : do_restart
neutral_y --> exit_instrument : not all_examination_done
neutral_y --> ready : all_examination_done
calibration --> fault : error<0
calibration --> restart : do_restart
final --> fault : error<0
final --> restart : do_restart
back_camera --> fault : error<0
back_camera --> restart : do_restart
back_camera --> move_to_examination_y : chinrest_adjusted
back_camera --> chinrest_adjustment : not chinrest_adjusted
move_to_examination_x --> fault : error<0
move_to_examination_x --> restart : do_restart
move_to_examination_x --> examination
move_to_examination_y --> fault : error<0
move_to_examination_y --> restart : do_restart
move_to_examination_y --> move_to_examination_x
emc_setup --> fault : error<0
emc_setup --> restart : do_restart
emc_prepare --> fault : error<0
emc_prepare --> restart : do_restart
examination --> fault : error<0
examination --> restart : do_restart
examination --> neutral_x
fault --> restart : do_restart
fault --> idle : rearm==1

@enduml
