@startuml

header
<font color=red>2021/08/09 10:43:53</font>
Filtered out target states:<font color=blue>['fault', 'restart']</font>
endheader

title = State Diagram: gen2 (filtered)

[*] --> idle

idle --> startup_check
idle : no_closing=False
init --> ready
startup_check --> init
restart --> idle
ready --> patient_init : new_patient==1
init_instrument --> patient_morpho_init : not patient_installed 
init_instrument --> back_camera : patient_installed 
exit_instrument --> prepare_examination
patient_init --> prepare_examination
patient_morpho_init --> patient_setup_adjustment
patient_morpho_init : chinrest_adjusted=False
patient_setup_adjustment --> patient_wait
chinrest_adjustment --> back_camera
patient_wait --> back_camera
patient_departure --> patient_left
prepare_examination --> init_instrument : not all_examination_done               
prepare_examination --> patient_departure : all_examination_done
patient_left --> neutral_x
neutral_x --> neutral_y
neutral_y --> exit_instrument : not all_examination_done
neutral_y --> ready : all_examination_done
back_camera --> move_to_examination_y : chinrest_adjusted
back_camera --> chinrest_adjustment : not chinrest_adjusted
move_to_examination_x --> examination
move_to_examination_y --> move_to_examination_x
examination --> neutral_x
fault --> idle : rearm==1

@enduml
