@startuml

header
<font color=red>2021/08/10 09:15:25</font>
endheader

title = State Diagram: emc_testing

[*] --> idle

idle --> init
idle --> fault : error<0
idle : no_closing=True
idle : do_init=True
idle : is_first_intrument=True
idle : emc_full_cycles=0
patient_setup --> fault : error<0
init --> ready : init_error==0
init --> fault : error<0
startup_check --> fault : error<0
restart --> fault : error<0
ready --> emc_patient_simulation
ready --> fault : error<0
init_instrument --> fault : error<0
exit_instrument --> fault : error<0
patient_init --> fault : error<0
patient_morpho_init --> fault : error<0
patient_setup_adjustment --> fault : error<0
chinrest_adjustment --> fault : error<0
patient_wait --> fault : error<0
dummy_examination --> fault : error<0
patient_departure --> fault : error<0
prepare_examination --> fault : error<0
patient_left --> fault : error<0
neutral_x --> neutral_y
neutral_x --> fault : error<0
neutral_y --> instrument_1_y : is_first_intrument
neutral_y --> instrument_2_y : not is_first_intrument
neutral_y --> fault : error<0
calibration --> fault : error<0
final --> fault : error<0
back_camera --> fault : error<0
move_to_examination_x --> fault : error<0
move_to_examination_y --> fault : error<0
instrument_1_x --> switch_instrument
instrument_1_x --> fault : error<0
instrument_1_y --> instrument_1_x
instrument_1_y --> fault : error<0
instrument_2_x --> switch_instrument
instrument_2_x --> fault : error<0
instrument_2_y --> instrument_2_x
instrument_2_y --> fault : error<0
switch_instrument --> neutral_x : not is_first_intrument
switch_instrument --> ready : is_first_intrument
switch_instrument --> fault : error<0
emc_patient_simulation --> neutral_x
emc_patient_simulation --> fault : error<0
examination --> fault : error<0

@enduml
